const PLAYER_HEIGHT_TILES = 3;
export const MIN_ROAD_WIDTH = Math.max(3, PLAYER_HEIGHT_TILES + 1);
export const PATH_CORRIDOR_WIDTH = MIN_ROAD_WIDTH;
export const EXIT_CORRIDOR_LENGTH = 8;
export const LANDING_INSET = 2;
export const LANDING_SAFE_RADIUS = 1;
export const ENTRANCE_CLEAR_ZONE_RADIUS = 4;
